### ISSUE TITLE
Extension needs to send a log data to the server

### ISSUE THREAD

**Issue by GedionT** [GedionT/Slice#5]
Data needs to be secured
Authentication is needed

**Comment by shivamsouravjha** [comment]
There's a authentication with Frontend and backend,we can do similar for backend and Extension.


Also we can encrypt the data for more safety.

**Comment by GedionT** [comment]
Yeah, I'm thinking to set the Backend to work without CORS, and then the extension calls auth routes to the API. 
What do you think?

**Comment by shivamsouravjha** [comment]
That's a great idea.

**Comment by shivamsouravjha** [comment]
Also I was thinking we connect the basic link Between backend and Extension,so that after finding the logger all we've to do is ~ replace the file,as the connection is already established.
